// Styling
import { openSans } from "@/utils/fonts/fonts";
import "./globals.css";
import GoogleAnalytics from "@/lib/google-analytics/googleAnalytics";
import CookieBanner from "@/ui/components/cookie-banner/cookie-banner.component";
import Navbar from "@/ui/components/nav-component/nav-bar.component";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        {/* <GoogleAnalytics GA_MEASUREMENT_ID={process.env.GA_MEASUREMENT_ID}/> */}
        <Navbar />
        {children}
        {/* <CookieBanner /> */}
      </body>
    </html>
  );
}
